name: londonmapbot

on:
  schedule:
    - cron: '0,30 * * * *'

jobs:
  twitter-dev-bot-post:
    runs-on: macOS-latest
    env:
      TWITTER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    steps:
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-renv@master
      - uses: r-lib/actions/setup-pandoc@master
      - name: Create and post tweet
        run: Rscript run.R
