name: twitter-dev-bot-post

on:
  workflow_dispatch:
  schedule:
    - cron: '0,30 * * * *'

jobs:

  twitter-dev-bot-post:
  
    runs-on: macOS-latest
    
    env:
      TWITTER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      
    steps:
    
      - uses: actions/checkout@v2
      
      - name: Checkout submodules
        run: git submodule update --init --recursive
      
      - uses: r-lib/actions/setup-r@v2
      
      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '2.19.2'
      
      - uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 2
        
      - name: Scrape, format and post
        run: Rscript run.R
